### ISSUE TITLE
KylinServerDiscovery

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#110]

**Comment by hit-lacus** [comment]
### kylin.log 
```sh
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "serviceType" (Class org.apache.curator.x.discovery.ServiceInstance), not marked as ignorable
 at [Source: [B@75c8491e; line: 1, column: 17] (through reference chain: org.apache.curator.x.discovery.ServiceInstance["serviceType"])
        at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
        at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:246)
        at org.codehaus.jackson.map.deser.StdDeserializer.reportUnknownProperty(StdDeserializer.java:604)
        at org.codehaus.jackson.map.deser.StdDeserializer.handleUnknownProperty(StdDeserializer.java:590)
        at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:689)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:514)
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:350)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2402)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1712)
        at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:50)
        at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:193)
        at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:96)
        at org.apache.kylin.common.zookeeper.KylinServerDiscovery.<init>(KylinServerDiscovery.java:116)
        ... 71 more
```

**Comment by hit-lacus** [comment]
[Loaded org.apache.jasper.xmlparser.ParserUtils from file:/root/xiaoxiang.yu/apache-kylin-3.1.0-SNAPSHOT-bin/tomcat/lib/jasper.jar]
[Loaded java.lang.Throwable$PrintStreamOrWriter from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/rt.jar]
[Loaded java.lang.Throwable$WrappedPrintWriter from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/rt.jar]
[Loaded java.util.IdentityHashMap$KeySet from /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/rt.jar]
Jun 22, 2020 3:22:01 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/kylin]]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1016)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:992)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.jasper.xmlparser.ParserUtils: method <init>()V not found
        at org.apache.jasper.runtime.TldScanner.scanTld(TldScanner.java:600)
        at org.apache.jasper.runtime.TldScanner.scanJar(TldScanner.java:457)
        at org.apache.jasper.runtime.TldScanner.scanJars(TldScanner.java:694)
        at org.apache.jasper.runtime.TldScanner.scanTlds(TldScanner.java:350)
        at org.apache.jasper.runtime.TldScanner.onStartup(TldScanner.java:239)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5709)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        ... 10 more
