### ISSUE TITLE
Regression Testing for Kylin 4.0-alpha 

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#115]

**Comment by hit-lacus** [comment]
ToC
// for Release Manager

**Comment by zhangayqian** [comment]
## Deploy env

#### $KYLIN_HOME
- job-node:   cdh-worker-2:/root/kylin-4-alpha/apache-kylin-4.0.0-SNAPSHOT-bin-job
- query-node:   cdh-worker-2:/root/kylin-4-alpha/apache-kylin-4.0.0-SNAPSHOT-bin-query

#### metadata url
- kylin.metadata.url=kylin_4_alpha@jdbc,url=jdbc:mysql://cdh-master:3306/kylin_test,username=kylin,password=R00t@kylin,maxActive=10,maxIdle=10

#### kylin url
- job-node: cdh-worker-2:7072
- query-node: cdh-worker-2:7073

**Comment by zhangayqian** [comment]
## Test report for Project Model Management
- The steps that have passed the verification have been checked on this page: 
https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=KYLIN&title=Test+Plan+of+Project+Model+Management

**Comment by RupengWang** [comment]
## Test report for Project Model Management
- The steps that have passed the verification have been checked on this page: 
https://cwiki.apache.org/confluence/display/KYLIN/Test+Plan+of+Data+source+Management

###  Detail report
#### Bug
- [KYLIN-4729](https://issues.apache.org/jira/browse/KYLIN-4729)

**Comment by hit-lacus** [comment]
#### AWS EMR测试失败
 
```
2020-08-31 11:26:42,361 ERROR [spark-entry-event-loop] application.JobWorkSpace:91 : Job failed eventually. Reason: Error occurred when generate retry configuration.
java.lang.NullPointerException
	at org.apache.spark.application.JobMonitor.handleResourceLack(JobMonitor.scala:48)
	at org.apache.spark.application.JobMonitor$$anon$1.onReceive(JobMonitor.scala:33)
	at org.apache.spark.scheduler.KylinJobEventLoop$$anonfun$onReceive$1.apply(KylinJobEventLoop.scala:42)
	at org.apache.spark.scheduler.KylinJobEventLoop$$anonfun$onReceive$1.apply(KylinJobEventLoop.scala:42)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.spark.scheduler.KylinJobEventLoop.onReceive(KylinJobEventLoop.scala:42)
	at org.apache.spark.scheduler.KylinJobEventLoop.onReceive(KylinJobEventLoop.scala:29)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
The command is:
export HADOOP_CONF_DIR=/etc/hadoop/conf && /root/spark-2.4.6-bin-hadoop2.7/bin/spark-submit --class org.apache.kylin.engine.spark.application.SparkEntry  --conf 'spark.hadoop.yarn.timeline-service.enabled=false'  --conf 'spark.executor.memoryOverhead=1024'  --conf 'spark.master=local'  --conf 'spark.executor.instances=40'  --conf 'spark.executor.memory=4G'  --conf 'spark.yarn.queue=default'  --conf 'spark.driver.cores=1'  --conf 'spark.history.fs.logDirectory=s3://xiaoxiang-yu/regression_testing/spark-history'  --conf 'spark.eventLog.enabled=true'  --conf 'spark.shuffle.service.enabled=true'  --conf 'spark.eventLog.dir=s3://xiaoxiang-yu/regression_testing/spark-history-event'  --conf 'spark.driver.memory=4096m'  --conf 'spark.driver.extraJavaOptions= -Dlog4j.configuration=file:/root/apache-kylin-4.0.0-SNAPSHOT-bin/conf/kylin-parquet-log4j.properties  -Dspark.driver.rest.server.ip=172.31.14.45  -Dspark.driver.param.taskId=3c42f552-e204-48fa-a66f-64fe54da95ff-00 '  --conf 'spark.sql.autoBroadcastJoinThreshold=-1'  --conf 'spark.sql.adaptive.enabled=false'  --conf 'spark.executor.extraClassPath=kylin-parquet-job-4.0.0-SNAPSHOT.jar'  --conf 'spark.driver.extraClassPath=/root/apache-kylin-4.0.0-SNAPSHOT-bin/lib/kylin-parquet-job-4.0.0-SNAPSHOT.jar' --name job_step_3c42f552-e204-48fa-a66f-64fe54da95ff-00 --jars /root/apache-kylin-4.0.0-SNAPSHOT-bin/lib/kylin-parquet-job-4.0.0-SNAPSHOT.jar /root/apache-kylin-4.0.0-SNAPSHOT-bin/lib/kylin-parquet-job-4.0.0-SNAPSHOT.jar -className org.apache.kylin.engine.spark.job.ResourceDetectBeforeCubingJob /root/apache-kylin-4.0.0-SNAPSHOT-bin/tomcat/temp/segmentIds3430941815963510607
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:214)
	at org.apache.kylin.job.execution.DefaultChainedExecutable.doWork(DefaultChainedExecutable.java:94)
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:197)
	... 4 more
Caused by: java.io.IOException: OS command error exit with return code: 1, error message: 2020-08-31 11:26:41,866 WARN  [main] util.NativeCodeLoader:62 : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-08-31 11:26:42,313 INFO  [pool-1-thread-1] application.SparkApplication:74 : Executor task org.apache.kylin.engine.spark.job.ResourceDetectBeforeCubingJob with args : {"distMetaUrl":"regression_testing@hdfs,path=s3://xiaoxiang-yu/regression_testing/regression_testing/learn_kylin/job_tmp/3c42f552-e204-48fa-a66f-64fe54da95ff-00/meta","submitter":"ADMIN","dataRangeEnd":"1357084800000","targetModel":"0928468a-9fab-4185-9a14-6f2e7c74823f","dataRangeStart":"1325376000000","project":"learn_kylin","className":"org.apache.kylin.engine.spark.job.ResourceDetectBeforeCubingJob","parentId":"3c42f552-e204-48fa-a66f-64fe54da95ff","jobId":"3c42f552-e204-48fa-a66f-64fe54da95ff","outputMetaUrl":"regression_testing@jdbc,url=jdbc:mysql://ip-172-31-14-45.cn-northwest-1.compute.internal:3306/hive,username=hive,password=Zpq2P74b4beZMjSE","segmentId":"715a8049-7702-7970-379b-cc04754e7839","cuboidsNum":"161","cubeName":"kylin_sales_cube","jobType":"BUILD","cubeId":"2fbca32a-a33e-4b69-83dd-0bb8b1f8c53b","segmentIds":"715a8049-7702-7970-379b-cc04754e7839"}
2020-08-31 11:26:42,322 INFO  [pool-1-thread-1] utils.MetaDumpUtil:119 : Ready to load KylinConfig from uri: regression_testing@hdfs,path=s3://xiaoxiang-yu/regression_testing/regression_testing/learn_kylin/job_tmp/3c42f552-e204-48fa-a66f-64fe54da95ff-00/meta
2020-08-31 11:26:42,356 ERROR [pool-1-thread-1] application.SparkApplication:77 : The spark job execute failed!
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.amazon.ws.emr.hadoop.fs.EmrFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.kylin.engine.spark.utils.MetaDumpUtil.loadKylinConfigFromHdfs(MetaDumpUtil.java:123)
	at org.apache.kylin.engine.spark.application.SparkApplication.execute(SparkApplication.java:124)
	at org.apache.kylin.engine.spark.application.SparkApplication.execute(SparkApplication.java:75)
	at org.apache.spark.application.JobWorker$$anon$2.run(JobWorker.scala:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: Class com.amazon.ws.emr.hadoop.fs.EmrFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	... 14 more

```

**Comment by xuekaiqi** [comment]
## Test report for Project Model Management
- The steps that have passed the verification have been checked on this page: 
https://cwiki.apache.org/confluence/display/KYLIN/Test+Plan+of+Cube+Management

###  Detail report
#### Bug
- [KYLIN-4732 The cube size is wrong after disabling the cube](https://issues.apache.org/jira/browse/KYLIN-4732)
- [KYLIN-4733 the cube size is inconsistent with the size of all segments](https://issues.apache.org/jira/browse/KYLIN-4733)
- [KYLIN-4734 the duration is still increasing after discarding the job](https://issues.apache.org/jira/browse/KYLIN-4734)

**Comment by zzcclp** [comment]
## Test report for Query Engine

**Comment by zzcclp** [comment]
## Test report for Operation
- The steps that have passed the verification have been checked on this page:
   https://cwiki.apache.org/confluence/display/KYLIN/Test+Plan+of+Operation

## Detail report

### Metastore
run command: bin/metastore.sh backup 
![image](https://user-images.githubusercontent.com/9430290/91935772-0ca40180-ed21-11ea-9ca1-9f087e59f35f.png)
![image](https://user-images.githubusercontent.com/9430290/91935818-20e7fe80-ed21-11ea-8dfc-739a1dfb4c89.png)

run command: 

### Cube Export/Import
run command: $KYLIN_HOME/bin/kylin.sh org.apache.kylin.tool.extractor.CubeMetaExtractor -cube kylin_sales_cube_query -destDir $KYLIN_HOME
![image](https://user-images.githubusercontent.com/9430290/91936909-65749980-ed23-11ea-81bb-355f2dff8b40.png)
