### ISSUE TITLE
KYLIN-3392 Verification

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#121]

**Comment by hit-lacus** [comment]
## Toc

**Comment by hit-lacus** [comment]
# Test Preparation


### Schema

create table kylin_3392 (
country string comment 'dimension',
city string comment 'dimension',
order_dt string comment 'dimension',
order_id string 'dimension or measure',

price_bigint bigint comment 'measure', 
price_double double comment 'measure', 
price_decimal decimal(12, 4) comment 'measure'
) stored as textfile ;


### Schema

```csv


```

**Comment by hit-lacus** [comment]
## Query in Hive

```sql
select city, 
    max(price_bigint), max(price_double), max(price_decimal),
    min(price_bigint), min(price_double), min(price_decimal),
    sum(price_bigint), sum(price_double), sum(price_decimal),
    count(price_bigint), count(price_double), count(price_decimal)
from test_3392
group by city;
```

**Comment by hit-lacus** [comment]
## Query in Kylin

```sql
select city, 
    max(price_bigint) mx1, max(price_double) mx2, max(price_decimal) mx3,
    min(price_bigint) mi1, min(price_double) mi2, min(price_decimal) mi3,
    sum(price_bigint) s1, sum(price_double) s2, sum(price_decimal) s3,
    count(price_bigint) c1, count(price_double) c2, count(price_decimal) c3
from test_3392
group by city;
```

- Before patch
```csv
CITY,MX1,MX2,MX3,MI1,MI2,MI3,S1,S2,S3,C1,C2,C3
New York,32298,32298.23,32298.23901,0,0.0,0,32298,32298.23,32298.23901,3,3,3
Shanghai,0,0.0,0,0,0.0,0,0,0.0,0,3,3,3
Tokyo,56556,56556.86,56556.85667,56556,56556.86,56556.85667,169668,169670.58000000002,169670.57001,3,3,3
London,43665,43665.03,43665.03471,0,0.0,0,87330,87330.06,87330.06942,3,3,3
Toronto,28910,28910.08,28910.08356,28910,28910.08,28910.08356,86730,86730.24,86730.25068,3,3,3
```

**Comment by hit-lacus** [comment]
## Cause Analysis

```sh
hbase(main):009:0* scan "KYLIN_N6FINFKDZU"
ROW                                     COLUMN+CELL
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=F1:M, timestamp=0, value=\x03\x05\x05\x02\x04\xF3\xDC,
 01\x00
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=F1:M, timestamp=0, value=\x03\x8F\x00
 01\x01
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=F1:M, timestamp=0, value=\x03\x05\x05\x03\xF3P\xBEi
 01\x02
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=F1:M, timestamp=0, value=\x03\x05\x05\x02\x08\x87\x1C^
 01\x03
 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x column=F1:M, timestamp=0, value=\x03\x05\x05\x00\xC0\x833\x9D
 01\x04
5 row(s) in 0.0150 seconds
```

**Comment by hit-lacus** [comment]
```
Destroy KylinConfig
Loading kylin-defaults.properties from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/core-common/target/classes/kylin-defaults.properties
Use KYLIN_CONF=../examples/test_metadata/
KYLIN_HOME was not set
Use KYLIN_CONF=../examples/test_metadata/
Initialized a new KylinConfig from getInstanceFromEnv : 1106131243
Kylin Config was updated with kylin.metadata.url : ../examples/test_metadata/
Kylin Config was updated with kylin.env.hdfs-working-dir : file:///tmp/kylin
Loading properties file from InputStream resource [resource loaded through InputStream]
Kylin metrics monitor is not enabled
Kylin service is starting.....
Using metadata url ../examples/test_metadata/ for resource store
Reloading AclRecord from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/server/../examples/test_metadata/acl
Loaded 1 AclRecord(s) out of 1 resource with 0 errors
Creating new manager instance of class org.apache.kylin.metadata.cachesync.Broadcaster
There is no available rest server; check the 'kylin.server.cluster-servers' config
0 nodes in the cluster: []
Kylin Config was updated with kylin.server.cluster-name : ../examples/test_metadata/
starting to initialize an instance in cluster ../examples/test_metadata/
Cluster servers: []
Kylin Config was updated with kylin.server.cluster-name : ../examples/test_metadata/
zookeeper connection string: localhost:12181 with namespace /examples/test_metadata
new zookeeper Client start: localhost:12181
Initializing Job Engine ....
77339@MBP-Kyligence.local trying to lock /job_engine/global_job_engine_lock
77339@MBP-Kyligence.local acquired lock at /job_engine/global_job_engine_lock
Starting resume all running jobs.
Creating new manager instance of class org.apache.kylin.job.execution.ExecutableManager
Using metadata url: ../examples/test_metadata/
Creating new manager instance of class org.apache.kylin.job.dao.ExecutableDao
Using metadata url: ../examples/test_metadata/
Reloading ExecutablePO from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/server/../examples/test_metadata/execute
Loaded 0 ExecutablePO(s) out of 0 resource with 0 errors
Reloading execute_output from /execute_output
Finishing resume all running jobs.
Fetching jobs every 30 seconds
Creating fetcher pool instance:1340493091
Creating new manager instance of class org.apache.kylin.metadata.badquery.BadQueryHistoryManager
Initializing BadQueryHistoryManager with config ../examples/test_metadata/
Use new version coordinator.
Using assigner DefaultAssigner
The version of ZooKeeper being used doesn't support Container nodes. CreateMode.PERSISTENT will be used instead.
Current node become the lead coordinator.
Restore job submitter
Creating new manager instance of class org.apache.kylin.rest.security.KylinUserManager
Initializing KylinUserManager with config ../examples/test_metadata/
Reloading ManagedUser from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/server/../examples/test_metadata/user
Loaded 0 ManagedUser(s) out of 0 resource with 0 errors
Saving ManagedUser at /user/ADMIN
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=ADMIN}
Saving ManagedUser at /user/MODELER
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=MODELER}
Saving ManagedUser at /user/ANALYST
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=ANALYST}

Destroy KylinConfig
Loading kylin-defaults.properties from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/core-common/target/classes/kylin-defaults.properties
Use KYLIN_CONF=../examples/test_metadata/
KYLIN_HOME was not set
Use KYLIN_CONF=../examples/test_metadata/
Initialized a new KylinConfig from getInstanceFromEnv : 1886186662
Kylin Config was updated with kylin.metadata.url : ../examples/test_metadata/
Kylin Config was updated with kylin.env.hdfs-working-dir : file:///tmp/kylin
Creating new manager instance of class org.apache.kylin.metadata.cachesync.Broadcaster
There is no available rest server; check the 'kylin.server.cluster-servers' config
0 nodes in the cluster: []
Broadcasting UPDATE, all, all
cleaning all storage cache
Closing HBase connections...
Close manager Broadcaster
Done broadcasting UPDATE, all, all
AnnounceThreadPool shutdown.
AnnounceMainLoop shutdown.
error running wiping
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at org.apache.kylin.metadata.cachesync.Broadcaster$1.run(Broadcaster.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Creating new manager instance of class org.apache.kylin.rest.security.KylinUserManager
Initializing KylinUserManager with config ../examples/test_metadata/
Using metadata url ../examples/test_metadata/ for resource store
Reloading ManagedUser from /Users/xiaoxiang.yu/IntelliJ_IDEA_Project/Kylin3/server/../examples/test_metadata/user
Loaded 0 ManagedUser(s) out of 0 resource with 0 errors
Creating new manager instance of class org.apache.kylin.metadata.cachesync.Broadcaster
There is no available rest server; check the 'kylin.server.cluster-servers' config
0 nodes in the cluster: []
Saving ManagedUser at /user/ADMIN
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=ADMIN}
Saving ManagedUser at /user/MODELER
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=MODELER}
Saving ManagedUser at /user/ANALYST
Servers in the cluster: []
Announcing new broadcast to all: BroadcastEvent{entity=user, event=create, cacheKey=ANALYST}
Job Fetcher: 0 should running, 0 actual running, 0 stopped, 0 ready, 0 already succeed, 0 error, 0 discarded, 0 others
Destroy KylinConfig



java.lang.AssertionError: 
Expected :1
Actual   :0
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.kylin.rest.metrics.QueryMetricsTest.testQueryMetrics(QueryMetricsTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Going to remove 1 cached curator clients
Shutting down DefaultScheduler ....
77339@MBP-Kyligence.local trying to unlock /job_engine/global_job_engine_lock
Closing HBase connections...
CuratorFramework for zkString localhost:12181 is removed due to EXPLICIT
77339@MBP-Kyligence.local failed to peekLock when unlock at /job_engine/global_job_engine_lock
org.apache.kylin.job.lock.zookeeper.exception.ZkPeekLockException: Error while peeking at /job_engine/global_job_engine_lock
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLock(ZookeeperDistributedLock.java:213)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.unlock(ZookeeperDistributedLock.java:245)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.unlockJobEngine(ZookeeperDistributedLock.java:359)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperJobLock.unlockJobEngine(ZookeeperJobLock.java:91)
	at org.apache.kylin.job.impl.threadpool.DefaultScheduler.shutdown(DefaultScheduler.java:187)
	at org.apache.kylin.rest.service.JobService$1.run(JobService.java:146)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Client is not started
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:310)
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:299)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:296)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:287)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:34)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLockInternal(ZookeeperDistributedLock.java:220)
Exception in thread "Thread-3" org.apache.kylin.job.lock.zookeeper.exception.ZkPeekLockException: Error while peeking at /job_engine/global_job_engine_lock
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLock(ZookeeperDistributedLock.java:208)
	... 6 more
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLock(ZookeeperDistributedLock.java:213)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.unlock(ZookeeperDistributedLock.java:245)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.unlockJobEngine(ZookeeperDistributedLock.java:359)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperJobLock.unlockJobEngine(ZookeeperJobLock.java:91)
	at org.apache.kylin.job.impl.threadpool.DefaultScheduler.shutdown(DefaultScheduler.java:187)
	at org.apache.kylin.rest.service.JobService$1.run(JobService.java:146)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Client is not started
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:310)
	at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:299)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:296)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:287)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:34)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLockInternal(ZookeeperDistributedLock.java:220)
	at org.apache.kylin.job.lock.zookeeper.ZookeeperDistributedLock.peekLock(ZookeeperDistributedLock.java:208)
	... 6 more

Process finished with exit code 255

```
