### ISSUE TITLE
Install HDP3.0 on RHEL 7

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#56]

**Comment by hit-lacus** [comment]
1

**Comment by hit-lacus** [comment]
2

**Comment by hit-lacus** [comment]
```sh
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@localhost ~]# free -h
              total        used        free      shared  buff/cache   available
Mem:            13G        181M         13G        8.4M        162M         13G
Swap:          7.1G          0B        7.1G
[root@localhost ~]# df -h
文件系统                 容量  已用  可用 已用% 挂载点
/dev/mapper/centos-root  243G  1.1G  242G    1% /
devtmpfs                 7.1G     0  7.1G    0% /dev
tmpfs                    7.0G     0  7.0G    0% /dev/shm
tmpfs                    7.0G  8.4M  7.0G    1% /run
tmpfs                    7.0G     0  7.0G    0% /sys/fs/cgroup
/dev/mapper/centos-home   50G   33M   50G    1% /home
/dev/xvda1               497M  126M  372M   26% /boot
tmpfs                    1.4G     0  1.4G    0% /run/user/0
```

**Comment by hit-lacus** [comment]
```sh
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.0/services/HIVE/package/scripts/hive_client.py", line 60, in <module>
    HiveClient().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 353, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.0/services/HIVE/package/scripts/hive_client.py", line 40, in install
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.0/services/HIVE/package/scripts/hive_client.py", line 48, in configure
    hive(name='client')
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.0/services/HIVE/package/scripts/hive.py", line 114, in hive
    jdbc_connector(params.hive_jdbc_target, params.hive_previous_jdbc_jar)
  File "/var/lib/ambari-agent/cache/stacks/HDP/3.0/services/HIVE/package/scripts/hive.py", line 628, in jdbc_connector
    File(params.downloaded_custom_connector, content = DownloadSource(params.driver_curl_source))
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 123, in action_create
    content = self._get_content()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 160, in _get_content
    return content()
  File "/usr/lib/ambari-agent/lib/resource_management/core/source.py", line 52, in __call__
    return self.get_content()
  File "/usr/lib/ambari-agent/lib/resource_management/core/source.py", line 197, in get_content
    raise Fail("Failed to download file from {0} due to HTTP error: {1}".format(self.url, str(ex)))
resource_management.core.exceptions.Fail: Failed to download file from http://hdp30:8080/resources/mysql-connector-java.jar due to HTTP error: HTTP Error 404: Not Found
```

**Comment by hit-lacus** [comment]
![image](https://user-images.githubusercontent.com/14030549/58378922-c1079180-7fce-11e9-8023-beb2a7b8e2a2.png)
