### ISSUE TITLE
Unresolved problem

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#85]

**Comment by hit-lacus** [comment]
```java
2020-01-19 17:00:51,895 ERROR [streaming_job_submitter-thread-1] execution.ExecutableManager:154 : fail to get job:b029378c-aacc-5b55-dc19-e4345b625519
org.apache.kylin.job.exception.PersistentException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=1, exceptions:
Sun Jan 19 17:00:51 CST 2020, RpcRetryingCaller{globalStartTime=1579424451894, pause=100, retries=1}, java.net.UnknownHostException: cdh-worker-1

	at org.apache.kylin.job.dao.ExecutableDao.getJob(ExecutableDao.java:347)
	at org.apache.kylin.job.execution.ExecutableManager.getJob(ExecutableManager.java:152)
	at org.apache.kylin.stream.coordinator.coordinate.BuildJobSubmitter.traceEarliestSegmentBuildJob(BuildJobSubmitter.java:192)
	at org.apache.kylin.stream.coordinator.coordinate.BuildJobSubmitter.doRun(BuildJobSubmitter.java:145)
	at org.apache.kylin.stream.coordinator.coordinate.BuildJobSubmitter.run(BuildJobSubmitter.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=1, exceptions:
Sun Jan 19 17:00:51 CST 2020, RpcRetryingCaller{globalStartTime=1579424451894, pause=100, retries=1}, java.net.UnknownHostException: cdh-worker-1

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:147)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:935)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:901)
	at org.apache.kylin.storage.hbase.HBaseResourceStore.internalGetFromHTable(HBaseResourceStore.java:472)
	at org.apache.kylin.storage.hbase.HBaseResourceStore.getFromHTable(HBaseResourceStore.java:450)
	at org.apache.kylin.storage.hbase.HBaseResourceStore.getResourceImpl(HBaseResourceStore.java:273)
	at org.apache.kylin.common.persistence.ResourceStore.lambda$getResourceWithRetry$1(ResourceStore.java:319)
	at org.apache.kylin.common.persistence.ExponentialBackoffRetry.doWithRetry(ExponentialBackoffRetry.java:52)
	at org.apache.kylin.common.persistence.ResourceStore.getResourceWithRetry(ResourceStore.java:319)
	at org.apache.kylin.common.persistence.ResourceStore.getResource(ResourceStore.java:296)
	at org.apache.kylin.common.persistence.ResourceStore.getResource(ResourceStore.java:287)
	at org.apache.kylin.job.dao.ExecutableDao.readJobResource(ExecutableDao.java:240)
	at org.apache.kylin.job.dao.ExecutableDao.getJob(ExecutableDao.java:344)
	... 11 more
Caused by: java.net.UnknownHostException: cdh-worker-1
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.<init>(AbstractRpcClient.java:315)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createBlockingRpcChannel(AbstractRpcClient.java:267)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getClient(ConnectionManager.java:1759)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:85)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:124)
	... 23 more
```

**Comment by hit-lacus** [comment]
```java
2020-02-11 19:56:23,370 INFO  [Scheduler 1520676144 Job 77e456c2-4f30-5c26-bb7b-cd091012f498-424] execution.ExecutableManager:475 : job id:77e456c2-4f30-5c26-bb7b-cd091012f498 from RUNNING to ERROR
2020-02-11 19:56:23,371 DEBUG [pool-12-thread-1] cachesync.Broadcaster:119 : Servers in the cluster: [localhost:7194]
2020-02-11 19:56:23,371 DEBUG [Scheduler 1520676144 Job 77e456c2-4f30-5c26-bb7b-cd091012f498-424] execution.AbstractExecutable:320 : no need to send email, user list is empty
2020-02-11 19:56:23,371 DEBUG [pool-12-thread-1] cachesync.Broadcaster:129 : Announcing new broadcast to all: BroadcastEvent{entity=execute_output, event=update, cacheKey=77e456c2-4f30-5c26-bb7b-cd091012f498}
2020-02-11 19:56:23,372 ERROR [pool-10-thread-10] threadpool.DefaultScheduler:116 : ExecuteException job:77e456c2-4f30-5c26-bb7b-cd091012f498
org.apache.kylin.job.exception.ExecuteException: org.apache.kylin.job.exception.ExecuteException: org.apache.kylin.engine.spark.exception.SparkException: OS command error exit with return code: 1, error message: LACUS [ WARN ]    02-11 19:56:19.988  org.apache.spark.internal.Logging.logWarning(Logging.scala:66)  from  main
 > The configuration key 'spark.yarn.executor.memoryOverhead' has been deprecated as of Spark 2.3 and may be removed in the future. Please use the new key 'spark.executor.memoryOverhead' instead.

SparkEntry args:-className org.apache.kylin.engine.spark.SparkCubingByLayer -hiveTable default.kylin_intermediate_kylin_sales_cube_spark_e4291d21_e96c_43af_2cd4_c43ab68e4eef -output hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_sales_cube_spark/cuboid/ -input hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_intermediate_kylin_sales_cube_spark_e4291d21_e96c_43af_2cd4_c43ab68e4eef -segmentId e4291d21-e96c-43af-2cd4-c43ab68e4eef -metaUrl 265rc1@hdfs,path=hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_sales_cube_spark/metadata -cubename kylin_sales_cube_spark
Running org.apache.kylin.engine.spark.SparkCubingByLayer -hiveTable default.kylin_intermediate_kylin_sales_cube_spark_e4291d21_e96c_43af_2cd4_c43ab68e4eef -output hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_sales_cube_spark/cuboid/ -input hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_intermediate_kylin_sales_cube_spark_e4291d21_e96c_43af_2cd4_c43ab68e4eef -segmentId e4291d21-e96c-43af-2cd4-c43ab68e4eef -metaUrl 265rc1@hdfs,path=hdfs://cdh-master:8020/kylin/265rc1/kylin-77e456c2-4f30-5c26-bb7b-cd091012f498/kylin_sales_cube_spark/metadata -cubename kylin_sales_cube_spark
Exception in thread "main" java.lang.RuntimeException: error execute org.apache.kylin.engine.spark.SparkCubingByLayer. Root cause: scala.reflect.ClassTag$$anon$1
	at org.apache.kylin.common.util.AbstractApplication.execute(AbstractApplication.java:42)
	at org.apache.kylin.common.util.SparkEntry.main(SparkEntry.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.ClassTag$$anon$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.kylin.engine.spark.SparkCubingByLayer.execute(SparkCubingByLayer.java:121)
	at org.apache.kylin.common.util.AbstractApplication.execute(AbstractApplication.java:37)
	... 13 more
LACUS [ INFO ]    02-11 19:56:21.130  org.apache.spark.internal.Logging.logInfo(Logging.scala:54)  from  Thread-1
 > Shutdown hook called
```

**Comment by zhiyuan192shine** [comment]
Xiaoxiang兄，请问 socket 大量处于CLOSE_WAIT 状态，这个问题现在有比较好的解决方式吗，这个问题有点让人尴尬

**Comment by hit-lacus** [comment]
@zhiyuan192shine  需要引入 https://github.com/apache/kylin/pull/1134 这个补丁就好了
