### ISSUE TITLE
Verification for Global Domain DIct

### ISSUE THREAD

**Issue by hit-lacus** [hit-lacus/hit-lacus.github.io#92]

**Comment by hit-lacus** [comment]
# Step  

### Create Parent Project


### Create and build cube in parent project

### Backup metadata 

### Create Childern Project

### Create and build cube in childern project

### Check query result and metadata

**Comment by hit-lacus** [comment]
# Mechanism

**Comment by hit-lacus** [comment]
# Test Result

**Comment by hit-lacus** [comment]
### ParentDictCube_01
```json
{
  "uuid": "0e6f1865-a563-84b2-09e0-afc822dc1303",
  "last_modified": 1581949263600,
  "version": "3.0.0.20500",
  "name": "ParentDictCube_01",
  "is_draft": false,
  "model_name": "ParentDictModel",
  "description": "",
  "null_string": null,
  "dimensions": [
    {
      "name": "UID",
      "table": "USERACTIONLOG",
      "column": "UID",
      "derived": null
    },
    {
      "name": "ACT_TYPE",
      "table": "USERACTIONLOG",
      "column": "ACT_TYPE",
      "derived": null
    },
    {
      "name": "PAGE_ID",
      "table": "USERACTIONLOG",
      "column": "PAGE_ID",
      "derived": null
    },
    {
      "name": "DEVICE_ID",
      "table": "USERACTIONLOG",
      "column": "DEVICE_ID",
      "derived": null
    },
    {
      "name": "DEVICE_BRAND",
      "table": "USERACTIONLOG",
      "column": "DEVICE_BRAND",
      "derived": null
    },
    {
      "name": "PART_DT",
      "table": "USERACTIONLOG",
      "column": "PART_DT",
      "derived": null
    }
  ],
  "measures": [
    {
      "name": "_COUNT_",
      "function": {
        "expression": "COUNT",
        "parameter": {
          "type": "constant",
          "value": "1"
        },
        "returntype": "bigint"
      }
    },
    {
      "name": "SUM_ACTIVE_MINUTES",
      "function": {
        "expression": "SUM",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.ACTIVE_MINUTES"
        },
        "returntype": "decimal(11,5)"
      }
    },
    {
      "name": "SUM_PLAY_DURATION",
      "function": {
        "expression": "SUM",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.PLAY_DURATION"
        },
        "returntype": "decimal(11,5)"
      }
    },
    {
      "name": "PV_BITMAP",
      "function": {
        "expression": "COUNT_DISTINCT",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.PV_ID"
        },
        "returntype": "bitmap"
      }
    },
    {
      "name": "TOP_ACTIVE_IN_REGISTER_DT",
      "function": {
        "expression": "TOP_N",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.ACTIVE_MINUTES",
          "next_parameter": {
            "type": "column",
            "value": "USERACTIONLOG.REGISTER_DATE"
          }
        },
        "returntype": "topn(100,4)",
        "configuration": {
          "topn.encoding.USERACTIONLOG.REGISTER_DATE": "dict",
          "topn.encoding_version.USERACTIONLOG.REGISTER_DATE": "1"
        }
      }
    }
  ],
  "dictionaries": [
    {
      "column": "USERACTIONLOG.PV_ID",
      "builder": "org.apache.kylin.dict.GlobalDictionaryBuilder",
      "cube": null,
      "model": null
    }
  ],
  "rowkey": {
    "rowkey_columns": [
      {
        "column": "USERACTIONLOG.UID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.ACT_TYPE",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.PAGE_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.DEVICE_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.DEVICE_BRAND",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.PART_DT",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      }
    ]
  },
  "hbase_mapping": {
    "column_family": [
      {
        "name": "F1",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "_COUNT_",
              "SUM_ACTIVE_MINUTES",
              "SUM_PLAY_DURATION",
              "TOP_ACTIVE_IN_REGISTER_DT"
            ]
          }
        ]
      },
      {
        "name": "F2",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "PV_BITMAP"
            ]
          }
        ]
      }
    ]
  },
  "aggregation_groups": [
    {
      "includes": [
        "USERACTIONLOG.UID",
        "USERACTIONLOG.ACT_TYPE",
        "USERACTIONLOG.PAGE_ID",
        "USERACTIONLOG.DEVICE_ID",
        "USERACTIONLOG.DEVICE_BRAND",
        "USERACTIONLOG.PART_DT"
      ],
      "select_rule": {
        "hierarchy_dims": [],
        "mandatory_dims": [],
        "joint_dims": [],
        "dim_cap": 1
      }
    }
  ],
  "signature": "HgZRz+OiaDgcpsTUXBszqQ==",
  "notify_list": [],
  "status_need_notify": [
    "ERROR",
    "DISCARDED",
    "SUCCEED"
  ],
  "partition_date_start": 0,
  "partition_date_end": 3153600000000,
  "auto_merge_time_ranges": [
    604800000,
    2419200000
  ],
  "volatile_range": 0,
  "retention_range": 0,
  "engine_type": 2,
  "storage_type": 2,
  "override_kylin_properties": {},
  "cuboid_black_list": [],
  "parent_forward": 3,
  "mandatory_dimension_set_list": [],
  "snapshot_table_desc_list": []
}
```

**Comment by hit-lacus** [comment]
### ParentDictCube_02
```json
{
  "uuid": "cad2607e-a288-03ac-cb59-755a75d47ee4",
  "last_modified": 1581949812162,
  "version": "3.0.0.20500",
  "name": "ParentDictCube_02",
  "is_draft": false,
  "model_name": "ParentDictModel",
  "description": "",
  "null_string": null,
  "dimensions": [
    {
      "name": "ITEM_ID",
      "table": "USERACTIONLOG",
      "column": "ITEM_ID",
      "derived": null
    },
    {
      "name": "ITEM_TYPE_ID",
      "table": "USERACTIONLOG",
      "column": "ITEM_TYPE_ID",
      "derived": null
    },
    {
      "name": "REGISTER_DATE",
      "table": "USERACTIONLOG",
      "column": "REGISTER_DATE",
      "derived": null
    },
    {
      "name": "LAST_LOGIN_DATE",
      "table": "USERACTIONLOG",
      "column": "LAST_LOGIN_DATE",
      "derived": null
    },
    {
      "name": "CITY",
      "table": "USERACTIONLOG",
      "column": "CITY",
      "derived": null
    },
    {
      "name": "PART_DT",
      "table": "USERACTIONLOG",
      "column": "PART_DT",
      "derived": null
    }
  ],
  "measures": [
    {
      "name": "_COUNT_",
      "function": {
        "expression": "COUNT",
        "parameter": {
          "type": "constant",
          "value": "1"
        },
        "returntype": "bigint"
      }
    },
    {
      "name": "SUM_PLAY_TIMES",
      "function": {
        "expression": "SUM",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.PLAY_TIMES"
        },
        "returntype": "bigint"
      }
    },
    {
      "name": "SUM_INTEREST_SCORE",
      "function": {
        "expression": "SUM",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.INTEREST_SCORE"
        },
        "returntype": "double"
      }
    },
    {
      "name": "PLAY_BITMAP",
      "function": {
        "expression": "COUNT_DISTINCT",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.PLAY_ID"
        },
        "returntype": "bitmap"
      }
    },
    {
      "name": "TOP_PLAY_IN_LAST_LOGIN",
      "function": {
        "expression": "TOP_N",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG.PLAY_DURATION",
          "next_parameter": {
            "type": "column",
            "value": "USERACTIONLOG.LAST_LOGIN_DATE"
          }
        },
        "returntype": "topn(10,4)",
        "configuration": {
          "topn.encoding.USERACTIONLOG.LAST_LOGIN_DATE": "dict",
          "topn.encoding_version.USERACTIONLOG.LAST_LOGIN_DATE": "1"
        }
      }
    }
  ],
  "dictionaries": [
    {
      "column": "USERACTIONLOG.PLAY_ID",
      "builder": "org.apache.kylin.dict.GlobalDictionaryBuilder",
      "cube": null,
      "model": null
    }
  ],
  "rowkey": {
    "rowkey_columns": [
      {
        "column": "USERACTIONLOG.ITEM_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.ITEM_TYPE_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.REGISTER_DATE",
        "encoding": "date",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.LAST_LOGIN_DATE",
        "encoding": "date",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.CITY",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG.PART_DT",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      }
    ]
  },
  "hbase_mapping": {
    "column_family": [
      {
        "name": "F1",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "_COUNT_",
              "SUM_PLAY_TIMES",
              "SUM_INTEREST_SCORE",
              "TOP_PLAY_IN_LAST_LOGIN"
            ]
          }
        ]
      },
      {
        "name": "F2",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "PLAY_BITMAP"
            ]
          }
        ]
      }
    ]
  },
  "aggregation_groups": [
    {
      "includes": [
        "USERACTIONLOG.ITEM_ID",
        "USERACTIONLOG.ITEM_TYPE_ID",
        "USERACTIONLOG.REGISTER_DATE",
        "USERACTIONLOG.LAST_LOGIN_DATE",
        "USERACTIONLOG.CITY",
        "USERACTIONLOG.PART_DT"
      ],
      "select_rule": {
        "hierarchy_dims": [],
        "mandatory_dims": [],
        "joint_dims": [],
        "dim_cap": 1
      }
    }
  ],
  "signature": "PIQipU4IG1ibVTQt1Mg3ZQ==",
  "notify_list": [],
  "status_need_notify": [
    "ERROR",
    "DISCARDED",
    "SUCCEED"
  ],
  "partition_date_start": 0,
  "partition_date_end": 3153600000000,
  "auto_merge_time_ranges": [
    604800000,
    2419200000
  ],
  "volatile_range": 0,
  "retention_range": 0,
  "engine_type": 2,
  "storage_type": 2,
  "override_kylin_properties": {},
  "cuboid_black_list": [],
  "parent_forward": 3,
  "mandatory_dimension_set_list": [],
  "snapshot_table_desc_list": []
}
```

**Comment by hit-lacus** [comment]
###

```json
{
  "uuid": "845be30e-87b7-8e01-9f1c-2e0f7d1f0a89",
  "last_modified": 1581952978090,
  "version": "3.0.0.20500",
  "name": "ReuseDictCube_MR_01",
  "is_draft": false,
  "model_name": "ChildDictModel",
  "description": "",
  "null_string": null,
  "dimensions": [
    {
      "name": "UID",
      "table": "USERACTIONLOG_COPY",
      "column": "UID",
      "derived": null
    },
    {
      "name": "ACT_TYPE",
      "table": "USERACTIONLOG_COPY",
      "column": "ACT_TYPE",
      "derived": null
    },
    {
      "name": "PAGE_ID",
      "table": "USERACTIONLOG_COPY",
      "column": "PAGE_ID",
      "derived": null
    },
    {
      "name": "DEVICE_ID",
      "table": "USERACTIONLOG_COPY",
      "column": "DEVICE_ID",
      "derived": null
    },
    {
      "name": "DEVICE_BRAND",
      "table": "USERACTIONLOG_COPY",
      "column": "DEVICE_BRAND",
      "derived": null
    }
  ],
  "measures": [
    {
      "name": "_COUNT_",
      "function": {
        "expression": "COUNT",
        "parameter": {
          "type": "constant",
          "value": "1"
        },
        "returntype": "bigint"
      }
    },
    {
      "name": "PV_BITMAP",
      "function": {
        "expression": "COUNT_DISTINCT",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG_COPY.PV_ID"
        },
        "returntype": "bitmap"
      }
    },
    {
      "name": "PLAY_BITMAP",
      "function": {
        "expression": "COUNT_DISTINCT",
        "parameter": {
          "type": "column",
          "value": "USERACTIONLOG_COPY.PLAY_ID"
        },
        "returntype": "bitmap"
      }
    }
  ],
  "dictionaries": [
    {
      "column": "USERACTIONLOG_COPY.PV_ID",
      "reuse": "USERACTIONLOG.PV_ID",
      "cube": "ParentDictCube_01",
      "model": "DomainDictionaryParentProject"
    },
    {
      "column": "USERACTIONLOG_COPY.PLAY_ID",
      "reuse": "USERACTIONLOG.PLAY_ID",
      "cube": "ParentDictCube_02",
      "model": "DomainDictionaryParentProject"
    }
  ],
  "rowkey": {
    "rowkey_columns": [
      {
        "column": "USERACTIONLOG_COPY.UID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG_COPY.ACT_TYPE",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG_COPY.PAGE_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG_COPY.DEVICE_ID",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      },
      {
        "column": "USERACTIONLOG_COPY.DEVICE_BRAND",
        "encoding": "dict",
        "encoding_version": 1,
        "isShardBy": false
      }
    ]
  },
  "hbase_mapping": {
    "column_family": [
      {
        "name": "F1",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "_COUNT_"
            ]
          }
        ]
      },
      {
        "name": "F2",
        "columns": [
          {
            "qualifier": "M",
            "measure_refs": [
              "PV_BITMAP",
              "PLAY_BITMAP"
            ]
          }
        ]
      }
    ]
  },
  "aggregation_groups": [
    {
      "includes": [
        "USERACTIONLOG_COPY.UID",
        "USERACTIONLOG_COPY.ACT_TYPE",
        "USERACTIONLOG_COPY.PAGE_ID",
        "USERACTIONLOG_COPY.DEVICE_ID",
        "USERACTIONLOG_COPY.DEVICE_BRAND"
      ],
      "select_rule": {
        "hierarchy_dims": [],
        "mandatory_dims": [],
        "joint_dims": []
      }
    }
  ],
  "signature": "9zJHOZNS5f6GIR5sikHkuw==",
  "notify_list": [],
  "status_need_notify": [
    "ERROR",
    "DISCARDED",
    "SUCCEED"
  ],
  "partition_date_start": 0,
  "partition_date_end": 3153600000000,
  "auto_merge_time_ranges": [
    604800000,
    2419200000
  ],
  "volatile_range": 0,
  "retention_range": 0,
  "engine_type": 2,
  "storage_type": 2,
  "override_kylin_properties": {},
  "cuboid_black_list": [],
  "parent_forward": 3,
  "mandatory_dimension_set_list": [],
  "snapshot_table_desc_list": []
}
```

**Comment by hit-lacus** [comment]
### Test 1 (Build Error)
```sh

2020-02-17 23:25:56,998 DEBUG [Scheduler 1736015793 Job c07e7f18-dbab-ccff-a6fa-d0c58584a742-341] execution.AbstractExecutable:332 : no need to send email, user list is empty
2020-02-17 23:25:56,999 DEBUG [http-bio-9005-exec-8] cachesync.Broadcaster:267 : Broadcasting UPDATE, execute_output, c07e7f18-dbab-ccff-a6fa-d0c58584a742
2020-02-17 23:25:57,000 DEBUG [http-bio-9005-exec-8] cachesync.Broadcaster:301 : Done broadcasting UPDATE, execute_output, c07e7f18-dbab-ccff-a6fa-d0c58584a742
2020-02-17 23:25:57,001 ERROR [pool-9-thread-7] threadpool.DefaultScheduler:116 : ExecuteException job:c07e7f18-dbab-ccff-a6fa-d0c58584a742
org.apache.kylin.job.exception.ExecuteException: org.apache.kylin.job.exception.ExecuteException: java.lang.NullPointerException
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:194)
	at org.apache.kylin.job.impl.threadpool.DefaultScheduler$JobRunner.run(DefaultScheduler.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kylin.job.exception.ExecuteException: java.lang.NullPointerException
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:194)
	at org.apache.kylin.job.execution.DefaultChainedExecutable.doWork(DefaultChainedExecutable.java:71)
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:179)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.apache.kylin.cube.model.CubeDescTiretreeGlobalDomainDictUtil.cuboidJob(CubeDescTiretreeGlobalDomainDictUtil.java:124)
	at org.apache.kylin.engine.mr.common.AbstractHadoopJob.attachSegmentMetadata(AbstractHadoopJob.java:591)
	at org.apache.kylin.engine.mr.common.AbstractHadoopJob.attachSegmentMetadataWithAll(AbstractHadoopJob.java:578)
	at org.apache.kylin.engine.mr.steps.CuboidJob.run(CuboidJob.java:134)
	at org.apache.kylin.engine.mr.common.MapReduceExecutable.doWork(MapReduceExecutable.java:144)
	at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:179)
	... 6 more
```

**Comment by hit-lacus** [comment]
### Some logs

#### Build Dimension Dictionary
```sh 
2020-02-18 00:55:05,569 INFO  [Scheduler 1320590272 Job e2f29438-ed3d-391c-0a27-821433494aee-210] model.CubeDesc:1382 : tiretree global domain dic : column DEFAULT.USERACTIONLOG_COPY.PV_ID use tiretree global domain dic, reuse column USERACTIONLOG.PV_ID
2020-02-18 00:55:05,569 INFO  [Scheduler 1320590272 Job e2f29438-ed3d-391c-0a27-821433494aee-210] model.CubeDesc:1382 : tiretree global domain dic : column DEFAULT.USERACTIONLOG_COPY.PLAY_ID use tiretree global domain dic, reuse column USERACTIONLOG.PLAY_ID
```

**Comment by hit-lacus** [comment]
![image](https://user-images.githubusercontent.com/14030549/74675144-e5a33980-51ed-11ea-973a-8bbe384770bc.png)

**Comment by hit-lacus** [comment]
![image](https://user-images.githubusercontent.com/14030549/74678900-4edb7a80-51f7-11ea-80f2-09a5748fd259.png)


![image](https://user-images.githubusercontent.com/14030549/74678929-5e5ac380-51f7-11ea-8517-77e819baf5cf.png)
